name: Release automation

on:
  push:
    branches:
      - main #-dont

jobs:
  build:

    name: Create Release
    runs-on: ubuntu-latest

    steps:
      - name: â¬‡ï¸ Checkout code
        uses: actions/checkout@v4
      
      - name: ğŸª¢ Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '21.x'
          registry-url: 'https://registry.npmjs.org'
      
      - name: âš™ï¸ npm install and build
        run: |
          npm install
          npm run build

      - name: ğŸ—œï¸ Creating artifact zip
        run: |
          ls -la
          zip -r dist.zip ./dist ./package.json

      - name: ğŸ”¢ Read version infos
        id: version-infos
        uses: jaywcjlove/github-action-read-file@main
        with:
          branch: main
          path: release.ver
      
      - name: ğŸ“„ Read version changelog
        id: version-chl
        uses: jaywcjlove/github-action-read-file@main
        with:
          branch: main
          path: release.chl

      - name: ğŸ› ï¸ Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          #steps.ghpages.outputs.content
          tag_name: ${{ steps.version-infos.outputs.content }}
          release_name: Release ${{ steps.version-infos.outputs.content }}
          body: |
            Changes in this Release
            ${{ steps.version-chl.outputs.content }}
          draft: false
          prerelease: false
          
      - name: â¬†ï¸ Upload artifact
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./dist.zip
          asset_name: directus-extension-harris-matrix.zip
          asset_content_type: application/zip
          
      - name: ğŸ“¦ Publish NPM package
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
